// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDywMjlqRqSfatxMwxFVYSmQZ_gyNU3yGM',
    appId: '1:293768342717:web:f278d84b912c51a81a5bd4',
    messagingSenderId: '293768342717',
    projectId: 'ds-chat-2b57b',
    authDomain: 'ds-chat-2b57b.firebaseapp.com',
    storageBucket: 'ds-chat-2b57b.appspot.com',
    measurementId: 'G-8WMTP6VR96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO7sg3ganK5eDcvNvq736-kDG_5CnCuK8',
    appId: '1:293768342717:android:f27ca7b12139bfa91a5bd4',
    messagingSenderId: '293768342717',
    projectId: 'ds-chat-2b57b',
    storageBucket: 'ds-chat-2b57b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmujDttFBoKAxXK9C3yty9AesY1-eK20',
    appId: '1:293768342717:ios:a9162bc4d28a3b021a5bd4',
    messagingSenderId: '293768342717',
    projectId: 'ds-chat-2b57b',
    storageBucket: 'ds-chat-2b57b.appspot.com',
    iosBundleId: 'com.example.dschat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmujDttFBoKAxXK9C3yty9AesY1-eK20',
    appId: '1:293768342717:ios:a9162bc4d28a3b021a5bd4',
    messagingSenderId: '293768342717',
    projectId: 'ds-chat-2b57b',
    storageBucket: 'ds-chat-2b57b.appspot.com',
    iosBundleId: 'com.example.dschat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDywMjlqRqSfatxMwxFVYSmQZ_gyNU3yGM',
    appId: '1:293768342717:web:d424d4e8a10461661a5bd4',
    messagingSenderId: '293768342717',
    projectId: 'ds-chat-2b57b',
    authDomain: 'ds-chat-2b57b.firebaseapp.com',
    storageBucket: 'ds-chat-2b57b.appspot.com',
    measurementId: 'G-J8VJ0J7ER7',
  );
}
